name: "Publish Docs"

on:
  workflow_run:
    workflows: ["CI"]
    branches: [master]
    types:
      - completed

jobs:
  publishing:
    name: Publish Documentation
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

    - name: 游닌 Checkout repository
      uses: actions/checkout@v3
      with:
        repository: input-output-hk/hydra
        ref: release
        # Also ensure we have all history with all tags
        fetch-depth: 0

    # TODO: Use the downloads below instead of these two steps after we have
    # released a version with new artifact names
    - name: 游닌 Download released benchmarks/haddocks
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: input-output-hk/hydra
        workflow: ci.yaml
        workflow_conclusion: success
        branch: release
        name: benchmarks-and-haddocks
        path: benchmarks-and-haddocks

    - name: Extract old released benchmarks/haddocks
      run: |
        mv benchmarks-and-haddocks/benchmarks/* docs/benchmarks/
        mv benchmarks-and-haddocks/static/haddock docs/static/

    # - name: 游닌 Download released benchmarks
    #   uses: dawidd6/action-download-artifact@v2
    #   with:
    #     repo: input-output-hk/hydra
    #     workflow: ci-nix.yaml
    #     workflow_conclusion: success
    #     branch: release
    #     name: benchmarks
    #     path: docs/benchmarks

    # - name: 游닌 Download released haddock documentation
    #   uses: dawidd6/action-download-artifact@v2
    #   with:
    #     repo: input-output-hk/hydra
    #     workflow: ci-nix.yaml
    #     workflow_conclusion: success
    #     branch: release
    #     name: haddocks
    #     path: docs/static/haddock

    - name: 游닌 Download released hydra-spec
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: input-output-hk/hydra
        workflow: ci.yaml
        workflow_conclusion: success
        branch: release
        name: hydra-spec
        path: docs/static

    - name: 游닌 Download released test-results
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: input-output-hk/hydra
        workflow: ci.yaml
        workflow_conclusion: success
        branch: release
        name: test-results
        path: docs/benchmarks/tests

    - name: Build documentation + latest monthly
      working-directory: docs
      run: |
        # TODO: redirect to /unstable/monthly instead?
        # Use monthly reports (blog) from master
        git checkout origin/master -- monthly/

        yarn
        yarn build

        mkdir -p /tmp/public
        mv build /tmp/public/head-protocol
        # Clean the working copy
        git clean -dxf

    - name: Checkout master
      working-directory: docs
      run: |
        git reset origin/master --hard
        sed -i 's|head-protocol|head-protocol/unstable|' docusaurus.config.js
        # TODO: debug
        find .

    - name: 游닌 Download latest hydra-spec
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: input-output-hk/hydra
        workflow: ci-nix.yaml
        workflow_conclusion: success
        branch: master
        name: hydra-spec
        path: docs/static

    - name: 游닌 Download latest benchmarks
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: input-output-hk/hydra
        workflow: ci-nix.yaml
        workflow_conclusion: success
        branch: master
        name: benchmarks
        path: docs/benchmarks

    - name: 游닌 Download latest test-results
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: input-output-hk/hydra
        workflow: ci-nix.yaml
        workflow_conclusion: success
        branch: master
        name: test-results
        path: docs/benchmarks/tests

    - name: 游닌 Download latest haddock documentation
      uses: dawidd6/action-download-artifact@v2
      with:
        repo: input-output-hk/hydra
        workflow: ci-nix.yaml
        workflow_conclusion: success
        branch: master
        name: haddocks
        path: docs/static/haddock

    - name: Build /unstable documentation
      working-directory: docs
      run: |
        yarn
        yarn build

        mv build /tmp/public/head-protocol/unstable

    - name: 游녤 Create redirect
      run: |
        echo "hydra.family" > /tmp/public/CNAME
        echo '<!DOCTYPE html><html><head><meta http-equiv="Refresh" content="0; URL=https://hydra.family/head-protocol"></head></html>' > /tmp/public/index.html

    - name: 游뚹 Publish Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN || github.token }}
        publish_dir: /tmp/public
        enable_jekyll: true
        force_orphan: true
